name: Deploy Infra

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SERVICE_PRINCIPLE_KEY: ${{ secrets.SERVICE_PRINCIPLE_KEY }}
          SERVICE_PRINCIPLE_ID: ${{ secrets.SERVICE_PRINCIPLE_ID }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
        name: Install Terraform Cli
      - run: terraform init
        working-directory: ./azure
        name: Initialize Terraform
      - run: terraform apply -var serviceprinciple_id=$SERVICE_PRINCIPLE_ID -var serviceprinciple_key=$SERVICE_PRINCIPLE_KEY -var tenant_id=$TENANT_ID -var subscription_id=SUBSCRIPTION_ID -var ssh_key="$SSH_KEY"
        working-directory: ./azure
        name: Deploy aks cluster



